"""empty message

Revision ID: 3d5f19edd4f0
Revises: 7106dcea3ec3
Create Date: 2016-01-09 17:34:57.166378

"""

# revision identifiers, used by Alembic.
revision = '3d5f19edd4f0'
down_revision = '7106dcea3ec3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battels', 'battelsid', new_column_name='battels_id',
                    existing_type=mysql.VARCHAR(length=6),
                    type_=mysql.VARCHAR(length=10),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battels', 'battels_id', new_column_name='battelsid',
                    existing_type=mysql.VARCHAR(length=10),
                    type_=mysql.VARCHAR(length=6),
                    nullable=True)
    ### end Alembic commands ###
