"""empty message

Revision ID: 40901b4f11c3
Revises: f2c58d294269
Create Date: 2016-01-23 18:04:10.751374

"""

# revision identifiers, used by Alembic.
revision = '40901b4f11c3'
down_revision = 'f2c58d294269'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_card_transaction')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_card_transaction',
    sa.Column('object_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('completed', mysql.DATETIME(), nullable=True),
    sa.Column('access_code', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('result_code', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('eway_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('refunded', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['object_id'], [u'transaction.object_id'], name=u'old_card_transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('object_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
