"""empty message

Revision ID: 57bc3837370a
Revises: 7edb23e128fe
Create Date: 2016-01-11 19:10:14.878086

"""

# revision identifiers, used by Alembic.
revision = '57bc3837370a'
down_revision = '7edb23e128fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('transaction_item', 'old_transaction_item')

    op.create_table('transaction_item',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum(u'Ticket', u'Generic', u'Postage'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], [u'transaction.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('generic_transaction_item',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('description', sa.Unicode(length=100), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], [u'transaction_item.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('postage_transaction_item',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('postage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], [u'transaction_item.object_id'], ),
    sa.ForeignKeyConstraint(['postage_id'], [u'postage.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('ticket_transaction_item',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('is_refund', sa.Boolean(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], [u'transaction_item.object_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], [u'ticket.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_transaction_item')
    op.drop_table('postage_transaction_item')
    op.drop_table('generic_transaction_item')
    op.drop_table('transaction_item')

    op.rename_table('old_transaction_item', 'transaction_item')
    ### end Alembic commands ###
