"""empty message

Revision ID: 57ed98de66db
Revises: 7d0bd13eb4a5
Create Date: 2016-05-03 12:22:43.796847

"""

# revision identifiers, used by Alembic.
revision = '57ed98de66db'
down_revision = '7d0bd13eb4a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('holds_ticket', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'holds_ticket')
    ### end Alembic commands ###
