"""empty message

Revision ID: 60159120a966
Revises: f90601546834
Create Date: 2016-01-14 15:20:11.206731

"""

# revision identifiers, used by Alembic.
revision = '60159120a966'
down_revision = 'f90601546834'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'transaction', ['transaction_id'], ['object_id'])

    op.alter_column('transaction_item', 'transaction_id', new_column_name='old_transaction_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)

    op.add_column('transaction_item', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key('transaction_item_ibfk_2', 'transaction_item', 'transaction', ['transaction_id'], ['object_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_item_ibfk_2', 'transaction_item', type_='foreignkey')
    op.drop_column('transaction_item', 'old_transaction_id')

    op.alter_column('transaction_item', 'old_transaction_id', new_column_name='transaction_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)

    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'transaction_id')
    ### end Alembic commands ###
