"""empty message

Revision ID: 60dffe3ee4be
Revises: 71a5df6794dc
Create Date: 2016-01-22 16:15:09.174737

"""

# revision identifiers, used by Alembic.
revision = '60dffe3ee4be'
down_revision = '71a5df6794dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_group', sa.Column('purchased', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_group', 'purchased')
    ### end Alembic commands ###
