"""empty message

Revision ID: 63011b54e21d
Revises: 5c5792caf593
Create Date: 2016-03-13 16:21:55.962114

"""

# revision identifiers, used by Alembic.
revision = '63011b54e21d'
down_revision = '5c5792caf593'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistic', 'group',
               existing_type=mysql.ENUM(u'college_users', u'payment_methods', u'ticket_types', u'total_ticket_sales', u'guest_ticket_sales', u'waiting'),
               type_=sa.Enum(u'college_users', u'total_ticket_sales', u'guest_ticket_sales', u'ticket_types', u'payment_methods', u'waiting', u'dietary_requirements'),
               existing_nullable=False)
    op.alter_column('transaction_item', 'item_type',
               existing_type=mysql.ENUM(u'Ticket', u'Generic', u'Postage'),
               type_=sa.Enum(u'Ticket', u'Generic', u'Postage', u'AdminFee'),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_item', 'item_type',
               existing_type=sa.Enum(u'Ticket', u'Generic', u'Postage', u'AdminFee'),
               type_=mysql.ENUM(u'Ticket', u'Generic', u'Postage'),
               existing_nullable=False)
    op.alter_column('statistic', 'group',
               existing_type=sa.Enum(u'college_users', u'total_ticket_sales', u'guest_ticket_sales', u'ticket_types', u'payment_methods', u'waiting', u'dietary_requirements'),
               type_=mysql.ENUM(u'college_users', u'payment_methods', u'ticket_types', u'total_ticket_sales', u'guest_ticket_sales', u'waiting'),
               existing_nullable=False)
    ### end Alembic commands ###
