"""empty message

Revision ID: 6546791fcdcb
Revises: 5b2ce9e13d39
Create Date: 2016-01-21 12:57:46.426148

"""

# revision identifiers, used by Alembic.
revision = '6546791fcdcb'
down_revision = '5b2ce9e13d39'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('use_noreply', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'use_noreply')
    ### end Alembic commands ###
