"""empty message

Revision ID: 7106dcea3ec3
Revises: 553fff6fd2be
Create Date: 2015-12-30 22:02:00.955112

"""

# revision identifiers, used by Alembic.
revision = '7106dcea3ec3'
down_revision = '553fff6fd2be'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'price', new_column_name='_price', existing_type=sa.Integer())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', '_price', new_column_name='price', existing_type=sa.Integer())
    ### end Alembic commands ###
