"""empty message

Revision ID: 7b6562ca688a
Revises: b75221b7534f
Create Date: 2016-01-14 13:49:36.044925

"""

# revision identifiers, used by Alembic.
revision = '7b6562ca688a'
down_revision = 'b75221b7534f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_transaction_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_transaction_item',
    sa.Column('object_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('item_type', mysql.ENUM(u'Ticket', u'Ticket Refund', u'Administration Fee', u'Postage'), nullable=False),
    sa.Column('_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('_description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('transaction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ticket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], [u'ticket.object_id'], name=u'old_transaction_item_ibfk_1'),
    sa.ForeignKeyConstraint(['transaction_id'], [u'transaction.object_id'], name=u'old_transaction_item_ibfk_2'),
    sa.PrimaryKeyConstraint('object_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
