"""empty message

Revision ID: 7d0bd13eb4a5
Revises: 9b2f6450ac61
Create Date: 2016-03-29 21:44:17.464827

"""

# revision identifiers, used by Alembic.
revision = '7d0bd13eb4a5'
down_revision = '9b2f6450ac61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'collected')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('collected', sa.Boolean(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
