"""empty message

Revision ID: 7edb23e128fe
Revises: 3d5f19edd4f0
Create Date: 2016-01-11 13:44:27.503770

"""

# revision identifiers, used by Alembic.
revision = '7edb23e128fe'
down_revision = '3d5f19edd4f0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postage',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('postage_type', sa.Unicode(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.Unicode(length=200), nullable=True),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('postage_ticket_link',
    sa.Column('postage_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postage_id'], [u'postage.object_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], [u'ticket.object_id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postage_ticket_link')
    op.drop_table('postage')
    ### end Alembic commands ###
