"""empty message

Revision ID: 878385c2bc9b
Revises: 9770bb643bca
Create Date: 2016-10-29 13:24:47.541663

"""

# revision identifiers, used by Alembic.
revision = '878385c2bc9b'
down_revision = '9770bb643bca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roundup_donation', 'base_donation_amt',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('roundup_donation', 'total_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roundup_donation', 'total_amount',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('roundup_donation', 'base_donation_amt',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    ### end Alembic commands ###
