"""empty message

Revision ID: 9770bb643bca
Revises: 3cbca143cf2d
Create Date: 2016-10-29 10:23:59.424998

"""

# revision identifiers, used by Alembic.
revision = '9770bb643bca'
down_revision = '3cbca143cf2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roundup_donation',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('base_donation_amt', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('charged_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['charged_to_id'], [u'user.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roundup_donation')
    ### end Alembic commands ###
