"""empty message

Revision ID: cb3b6eb44c9d
Revises: 7b6562ca688a
Create Date: 2016-01-14 14:09:33.268926

"""

# revision identifiers, used by Alembic.
revision = 'cb3b6eb44c9d'
down_revision = '7b6562ca688a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'completed')
    op.drop_column('transaction', 'address')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('address', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('transaction', sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    ### end Alembic commands ###
