"""empty message

Revision ID: cc35d35089f4
Revises: 60dffe3ee4be
Create Date: 2016-01-22 17:17:42.750149

"""

# revision identifiers, used by Alembic.
revision = 'cc35d35089f4'
down_revision = '60dffe3ee4be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('purchase_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'purchase_group', ['purchase_group_id'], ['object_id'])
    op.add_column('purchase_group', sa.Column('disbanded', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_group', 'disbanded')
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'purchase_group_id')
    ### end Alembic commands ###
