"""empty message

Revision ID: f7a69be715b3
Revises: 5ce00ca1cea8
Create Date: 2016-02-10 19:46:11.975174

"""

# revision identifiers, used by Alembic.
revision = 'f7a69be715b3'
down_revision = '5ce00ca1cea8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('verified', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'verified')
    ### end Alembic commands ###
