"""empty message

Revision ID: f90601546834
Revises: cb3b6eb44c9d
Create Date: 2016-01-14 14:33:12.532772

"""

# revision identifiers, used by Alembic.
revision = 'f90601546834'
down_revision = 'cb3b6eb44c9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('transaction', 'old_transaction')
    op.rename_table('card_transaction', 'old_card_transaction')

    op.create_table('transaction',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum(u'Battels', u'Card', u'Free'), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'user.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('battels_transaction',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('battels_term', sa.Unicode(length=4), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], [u'transaction.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('card_transaction',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('access_code', sa.Unicode(length=200), nullable=True),
    sa.Column('result_code', sa.Unicode(length=2), nullable=True),
    sa.Column('eway_id', sa.Integer(), nullable=True),
    sa.Column('refunded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], [u'transaction.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_transaction')
    op.drop_table('battels_transaction')
    op.drop_table('transaction')

    op.rename_table('old_transaction', 'transaction')
    op.rename_table('old_card_transaction', 'card_transaction')
    ### end Alembic commands ###
