"""empty message

Revision ID: fac5a30043f2
Revises: f7a69be715b3
Create Date: 2016-02-12 14:26:53.375821

"""

# revision identifiers, used by Alembic.
revision = 'fac5a30043f2'
down_revision = 'f7a69be715b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('claim_code', sa.Unicode(length=17), nullable=True))
    op.add_column('ticket', sa.Column('claims_made', sa.Integer(), nullable=False))
    op.add_column('ticket', sa.Column('holder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'user', ['holder_id'], ['object_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'holder_id')
    op.drop_column('ticket', 'claims_made')
    op.drop_column('ticket', 'claim_code')
    ### end Alembic commands ###
